//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETD.Properties {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2015 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "2.6.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
#if !SILVERLIGHT
    [global::System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=true)]
#endif
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces")]
    public partial class Resources {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        /// <summary>
        /// Initializes a Resources object.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        /// Thread safe lock object used by this class.
        /// </summary>
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    global::System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    global::System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            global::System.Threading.Interlocked.Exchange(ref _resourceManager, new global::System.Resources.ResourceManager("ETD.Properties.Resources", typeof(Resources).Assembly));
                        }
                    }
                    finally {
                        global::System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Add Equipment'.
        /// </summary>
        public static string Button_AddEquipment {
            get {
                return ResourceManager.GetString(ResourceNames.Button_AddEquipment, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Add Member'.
        /// </summary>
        public static string Button_AddMember {
            get {
                return ResourceManager.GetString(ResourceNames.Button_AddMember, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Cancel'.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString(ResourceNames.Button_Cancel, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Follow Up'.
        /// </summary>
        public static string Button_FollowUp {
            get {
                return ResourceManager.GetString(ResourceNames.Button_FollowUp, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'GPS Location'.
        /// </summary>
        public static string Button_GPSLocations {
            get {
                return ResourceManager.GetString(ResourceNames.Button_GPSLocations, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Load Map'.
        /// </summary>
        public static string Button_LoadMap {
            get {
                return ResourceManager.GetString(ResourceNames.Button_LoadMap, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Remove Member'.
        /// </summary>
        public static string Button_RemoveMember {
            get {
                return ResourceManager.GetString(ResourceNames.Button_RemoveMember, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Submit'.
        /// </summary>
        public static string Button_Submit {
            get {
                return ResourceManager.GetString(ResourceNames.Button_Submit, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Ambulance Cart'.
        /// </summary>
        public static string ComboBoxItem_AmbulanceCart {
            get {
                return ResourceManager.GetString(ResourceNames.ComboBoxItem_AmbulanceCart, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Camp'.
        /// </summary>
        public static string ComboBoxItem_Camp {
            get {
                return ResourceManager.GetString(ResourceNames.ComboBoxItem_Camp, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Circle'.
        /// </summary>
        public static string ComboBoxItem_Circle {
            get {
                return ResourceManager.GetString(ResourceNames.ComboBoxItem_Circle, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Edit Mode'.
        /// </summary>
        public static string ComboBoxItem_EditMode {
            get {
                return ResourceManager.GetString(ResourceNames.ComboBoxItem_EditMode, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Epipen'.
        /// </summary>
        public static string ComboBoxItem_Epipen {
            get {
                return ResourceManager.GetString(ResourceNames.ComboBoxItem_Epipen, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'First Responder'.
        /// </summary>
        public static string ComboBoxItem_FirstResponder {
            get {
                return ResourceManager.GetString(ResourceNames.ComboBoxItem_FirstResponder, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'General First Aid'.
        /// </summary>
        public static string ComboBoxItem_GeneralFA {
            get {
                return ResourceManager.GetString(ResourceNames.ComboBoxItem_GeneralFA, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Line'.
        /// </summary>
        public static string ComboBoxItem_Line {
            get {
                return ResourceManager.GetString(ResourceNames.ComboBoxItem_Line, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Medicine'.
        /// </summary>
        public static string ComboBoxItem_Medicine {
            get {
                return ResourceManager.GetString(ResourceNames.ComboBoxItem_Medicine, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Mounted Stretcher'.
        /// </summary>
        public static string ComboBoxItem_MountedStretcher {
            get {
                return ResourceManager.GetString(ResourceNames.ComboBoxItem_MountedStretcher, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Rectangle'.
        /// </summary>
        public static string ComboBoxItem_Rectangle {
            get {
                return ResourceManager.GetString(ResourceNames.ComboBoxItem_Rectangle, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Regular Mode'.
        /// </summary>
        public static string ComboBoxItem_RegularMode {
            get {
                return ResourceManager.GetString(ResourceNames.ComboBoxItem_RegularMode, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Sitting Cart'.
        /// </summary>
        public static string ComboBoxItem_SittingCart {
            get {
                return ResourceManager.GetString(ResourceNames.ComboBoxItem_SittingCart, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Stairs'.
        /// </summary>
        public static string ComboBoxItem_Stairs {
            get {
                return ResourceManager.GetString(ResourceNames.ComboBoxItem_Stairs, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Transport Stretcher'.
        /// </summary>
        public static string ComboBoxItem_TransportStretcher {
            get {
                return ResourceManager.GetString(ResourceNames.ComboBoxItem_TransportStretcher, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Wheelchair'.
        /// </summary>
        public static string ComboBoxItem_Wheelchair {
            get {
                return ResourceManager.GetString(ResourceNames.ComboBoxItem_Wheelchair, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Acronym'.
        /// </summary>
        public static string Label_Acronym {
            get {
                return ResourceManager.GetString(ResourceNames.Label_Acronym, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Time of Departure'.
        /// </summary>
        public static string Label_DepartureTime {
            get {
                return ResourceManager.GetString(ResourceNames.Label_DepartureTime, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Dispatcher Name'.
        /// </summary>
        public static string Label_DispatcherName {
            get {
                return ResourceManager.GetString(ResourceNames.Label_DispatcherName, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Completed'.
        /// </summary>
        public static string Label_InterventionFilterCompleted {
            get {
                return ResourceManager.GetString(ResourceNames.Label_InterventionFilterCompleted, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Ongoing'.
        /// </summary>
        public static string Label_InterventionFilterOngoing {
            get {
                return ResourceManager.GetString(ResourceNames.Label_InterventionFilterOngoing, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Interventions:'.
        /// </summary>
        public static string Label_Interventions {
            get {
                return ResourceManager.GetString(ResourceNames.Label_Interventions, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Operation Name'.
        /// </summary>
        public static string Label_OperationName {
            get {
                return ResourceManager.GetString(ResourceNames.Label_OperationName, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Shift End Date'.
        /// </summary>
        public static string Label_ShiftEndDate {
            get {
                return ResourceManager.GetString(ResourceNames.Label_ShiftEndDate, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Shift End Time'.
        /// </summary>
        public static string Label_ShiftEndTime {
            get {
                return ResourceManager.GetString(ResourceNames.Label_ShiftEndTime, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Shift Start Date'.
        /// </summary>
        public static string Label_ShiftStartDate {
            get {
                return ResourceManager.GetString(ResourceNames.Label_ShiftStartDate, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Shift Start Time'.
        /// </summary>
        public static string Label_ShiftStartTime {
            get {
                return ResourceManager.GetString(ResourceNames.Label_ShiftStartTime, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Teams'.
        /// </summary>
        public static string Label_Teams {
            get {
                return ResourceManager.GetString(ResourceNames.Label_Teams, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Training:'.
        /// </summary>
        public static string Label_Training {
            get {
                return ResourceManager.GetString(ResourceNames.Label_Training, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Completed Interventions'.
        /// </summary>
        public static string MenuItem_CompletedInterventions {
            get {
                return ResourceManager.GetString(ResourceNames.MenuItem_CompletedInterventions, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Delete Team'.
        /// </summary>
        public static string MenuItem_DeleteTeam {
            get {
                return ResourceManager.GetString(ResourceNames.MenuItem_DeleteTeam, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Ongoing Interventions'.
        /// </summary>
        public static string MenuItem_OngoingInterventions {
            get {
                return ResourceManager.GetString(ResourceNames.MenuItem_OngoingInterventions, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'ABC'.
        /// </summary>
        public static string TabItem_ABC {
            get {
                return ResourceManager.GetString(ResourceNames.TabItem_ABC, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Additional Info'.
        /// </summary>
        public static string TabItem_AdditionalInfo {
            get {
                return ResourceManager.GetString(ResourceNames.TabItem_AdditionalInfo, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Details'.
        /// </summary>
        public static string TabItem_Details {
            get {
                return ResourceManager.GetString(ResourceNames.TabItem_Details, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'End'.
        /// </summary>
        public static string TabItem_End {
            get {
                return ResourceManager.GetString(ResourceNames.TabItem_End, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Resources'.
        /// </summary>
        public static string TabItem_Resources {
            get {
                return ResourceManager.GetString(ResourceNames.TabItem_Resources, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Timers'.
        /// </summary>
        public static string TabItem_Timers {
            get {
                return ResourceManager.GetString(ResourceNames.TabItem_Timers, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Deadlines (mins):'.
        /// </summary>
        public static string TextBlock_Deadlines {
            get {
                return ResourceManager.GetString(ResourceNames.TextBlock_Deadlines, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Intervention'.
        /// </summary>
        public static string TextBlock_InterventionDeadline {
            get {
                return ResourceManager.GetString(ResourceNames.TextBlock_InterventionDeadline, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Moving'.
        /// </summary>
        public static string TextBlock_MovingDeadline {
            get {
                return ResourceManager.GetString(ResourceNames.TextBlock_MovingDeadline, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Team Member Name'.
        /// </summary>
        public static string TextBox_TeamMemberName {
            get {
                return ResourceManager.GetString(ResourceNames.TextBox_TeamMemberName, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Team Name'.
        /// </summary>
        public static string TextBox_TeamName {
            get {
                return ResourceManager.GetString(ResourceNames.TextBox_TeamName, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Lists all the resource names as constant string fields.
        /// </summary>
        public class ResourceNames {
            
            /// <summary>
            /// Stores the resource name 'Button_AddEquipment'.
            /// </summary>
            public const string Button_AddEquipment = "Button_AddEquipment";
            
            /// <summary>
            /// Stores the resource name 'Button_AddMember'.
            /// </summary>
            public const string Button_AddMember = "Button_AddMember";
            
            /// <summary>
            /// Stores the resource name 'Button_Cancel'.
            /// </summary>
            public const string Button_Cancel = "Button_Cancel";
            
            /// <summary>
            /// Stores the resource name 'Button_FollowUp'.
            /// </summary>
            public const string Button_FollowUp = "Button_FollowUp";
            
            /// <summary>
            /// Stores the resource name 'Button_GPSLocations'.
            /// </summary>
            public const string Button_GPSLocations = "Button_GPSLocations";
            
            /// <summary>
            /// Stores the resource name 'Button_LoadMap'.
            /// </summary>
            public const string Button_LoadMap = "Button_LoadMap";
            
            /// <summary>
            /// Stores the resource name 'Button_RemoveMember'.
            /// </summary>
            public const string Button_RemoveMember = "Button_RemoveMember";
            
            /// <summary>
            /// Stores the resource name 'Button_Submit'.
            /// </summary>
            public const string Button_Submit = "Button_Submit";
            
            /// <summary>
            /// Stores the resource name 'ComboBoxItem_AmbulanceCart'.
            /// </summary>
            public const string ComboBoxItem_AmbulanceCart = "ComboBoxItem_AmbulanceCart";
            
            /// <summary>
            /// Stores the resource name 'ComboBoxItem_Camp'.
            /// </summary>
            public const string ComboBoxItem_Camp = "ComboBoxItem_Camp";
            
            /// <summary>
            /// Stores the resource name 'ComboBoxItem_Circle'.
            /// </summary>
            public const string ComboBoxItem_Circle = "ComboBoxItem_Circle";
            
            /// <summary>
            /// Stores the resource name 'ComboBoxItem_EditMode'.
            /// </summary>
            public const string ComboBoxItem_EditMode = "ComboBoxItem_EditMode";
            
            /// <summary>
            /// Stores the resource name 'ComboBoxItem_Epipen'.
            /// </summary>
            public const string ComboBoxItem_Epipen = "ComboBoxItem_Epipen";
            
            /// <summary>
            /// Stores the resource name 'ComboBoxItem_FirstResponder'.
            /// </summary>
            public const string ComboBoxItem_FirstResponder = "ComboBoxItem_FirstResponder";
            
            /// <summary>
            /// Stores the resource name 'ComboBoxItem_GeneralFA'.
            /// </summary>
            public const string ComboBoxItem_GeneralFA = "ComboBoxItem_GeneralFA";
            
            /// <summary>
            /// Stores the resource name 'ComboBoxItem_Line'.
            /// </summary>
            public const string ComboBoxItem_Line = "ComboBoxItem_Line";
            
            /// <summary>
            /// Stores the resource name 'ComboBoxItem_Medicine'.
            /// </summary>
            public const string ComboBoxItem_Medicine = "ComboBoxItem_Medicine";
            
            /// <summary>
            /// Stores the resource name 'ComboBoxItem_MountedStretcher'.
            /// </summary>
            public const string ComboBoxItem_MountedStretcher = "ComboBoxItem_MountedStretcher";
            
            /// <summary>
            /// Stores the resource name 'ComboBoxItem_Rectangle'.
            /// </summary>
            public const string ComboBoxItem_Rectangle = "ComboBoxItem_Rectangle";
            
            /// <summary>
            /// Stores the resource name 'ComboBoxItem_RegularMode'.
            /// </summary>
            public const string ComboBoxItem_RegularMode = "ComboBoxItem_RegularMode";
            
            /// <summary>
            /// Stores the resource name 'ComboBoxItem_SittingCart'.
            /// </summary>
            public const string ComboBoxItem_SittingCart = "ComboBoxItem_SittingCart";
            
            /// <summary>
            /// Stores the resource name 'ComboBoxItem_Stairs'.
            /// </summary>
            public const string ComboBoxItem_Stairs = "ComboBoxItem_Stairs";
            
            /// <summary>
            /// Stores the resource name 'ComboBoxItem_TransportStretcher'.
            /// </summary>
            public const string ComboBoxItem_TransportStretcher = "ComboBoxItem_TransportStretcher";
            
            /// <summary>
            /// Stores the resource name 'ComboBoxItem_Wheelchair'.
            /// </summary>
            public const string ComboBoxItem_Wheelchair = "ComboBoxItem_Wheelchair";
            
            /// <summary>
            /// Stores the resource name 'Label_Acronym'.
            /// </summary>
            public const string Label_Acronym = "Label_Acronym";
            
            /// <summary>
            /// Stores the resource name 'Label_DepartureTime'.
            /// </summary>
            public const string Label_DepartureTime = "Label_DepartureTime";
            
            /// <summary>
            /// Stores the resource name 'Label_DispatcherName'.
            /// </summary>
            public const string Label_DispatcherName = "Label_DispatcherName";
            
            /// <summary>
            /// Stores the resource name 'Label_InterventionFilterCompleted'.
            /// </summary>
            public const string Label_InterventionFilterCompleted = "Label_InterventionFilterCompleted";
            
            /// <summary>
            /// Stores the resource name 'Label_InterventionFilterOngoing'.
            /// </summary>
            public const string Label_InterventionFilterOngoing = "Label_InterventionFilterOngoing";
            
            /// <summary>
            /// Stores the resource name 'Label_Interventions'.
            /// </summary>
            public const string Label_Interventions = "Label_Interventions";
            
            /// <summary>
            /// Stores the resource name 'Label_OperationName'.
            /// </summary>
            public const string Label_OperationName = "Label_OperationName";
            
            /// <summary>
            /// Stores the resource name 'Label_ShiftEndDate'.
            /// </summary>
            public const string Label_ShiftEndDate = "Label_ShiftEndDate";
            
            /// <summary>
            /// Stores the resource name 'Label_ShiftEndTime'.
            /// </summary>
            public const string Label_ShiftEndTime = "Label_ShiftEndTime";
            
            /// <summary>
            /// Stores the resource name 'Label_ShiftStartDate'.
            /// </summary>
            public const string Label_ShiftStartDate = "Label_ShiftStartDate";
            
            /// <summary>
            /// Stores the resource name 'Label_ShiftStartTime'.
            /// </summary>
            public const string Label_ShiftStartTime = "Label_ShiftStartTime";
            
            /// <summary>
            /// Stores the resource name 'Label_Teams'.
            /// </summary>
            public const string Label_Teams = "Label_Teams";
            
            /// <summary>
            /// Stores the resource name 'Label_Training'.
            /// </summary>
            public const string Label_Training = "Label_Training";
            
            /// <summary>
            /// Stores the resource name 'MenuItem_CompletedInterventions'.
            /// </summary>
            public const string MenuItem_CompletedInterventions = "MenuItem_CompletedInterventions";
            
            /// <summary>
            /// Stores the resource name 'MenuItem_DeleteTeam'.
            /// </summary>
            public const string MenuItem_DeleteTeam = "MenuItem_DeleteTeam";
            
            /// <summary>
            /// Stores the resource name 'MenuItem_OngoingInterventions'.
            /// </summary>
            public const string MenuItem_OngoingInterventions = "MenuItem_OngoingInterventions";
            
            /// <summary>
            /// Stores the resource name 'TabItem_ABC'.
            /// </summary>
            public const string TabItem_ABC = "TabItem_ABC";
            
            /// <summary>
            /// Stores the resource name 'TabItem_AdditionalInfo'.
            /// </summary>
            public const string TabItem_AdditionalInfo = "TabItem_AdditionalInfo";
            
            /// <summary>
            /// Stores the resource name 'TabItem_Details'.
            /// </summary>
            public const string TabItem_Details = "TabItem_Details";
            
            /// <summary>
            /// Stores the resource name 'TabItem_End'.
            /// </summary>
            public const string TabItem_End = "TabItem_End";
            
            /// <summary>
            /// Stores the resource name 'TabItem_Resources'.
            /// </summary>
            public const string TabItem_Resources = "TabItem_Resources";
            
            /// <summary>
            /// Stores the resource name 'TabItem_Timers'.
            /// </summary>
            public const string TabItem_Timers = "TabItem_Timers";
            
            /// <summary>
            /// Stores the resource name 'TextBlock_Deadlines'.
            /// </summary>
            public const string TextBlock_Deadlines = "TextBlock_Deadlines";
            
            /// <summary>
            /// Stores the resource name 'TextBlock_InterventionDeadline'.
            /// </summary>
            public const string TextBlock_InterventionDeadline = "TextBlock_InterventionDeadline";
            
            /// <summary>
            /// Stores the resource name 'TextBlock_MovingDeadline'.
            /// </summary>
            public const string TextBlock_MovingDeadline = "TextBlock_MovingDeadline";
            
            /// <summary>
            /// Stores the resource name 'TextBox_TeamMemberName'.
            /// </summary>
            public const string TextBox_TeamMemberName = "TextBox_TeamMemberName";
            
            /// <summary>
            /// Stores the resource name 'TextBox_TeamName'.
            /// </summary>
            public const string TextBox_TeamName = "TextBox_TeamName";
        }
    }
}
